name: SlotPlugin
version: 1.0-SNAPSHOT
main: tamakake.slotPlugin.SlotPlugin
api-version: "1.21"
commands:
  giveslot:
    description: スロット設置ツールを取得
    usage: /giveslot
    permission: tamakake.slot.op
    permission-message: "権限がありません"
  getticket:
    description: スロットチケットを手動で取得
    usage: /getticket
    permission: tamakake.slot.op
    permission-message: "権限がありません"